name: My node.js CI workflow

on:
  push:
    paths:
      - '1-cap/**'
  pull_request:
    paths:
      - '1-cap/**'
  workflow_dispatch:
    inputs:
      log-level:
        description: 'Log level'
        required: true
        default: 'info'

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-cap
    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - run: echo "I'm running to install nodejs"
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        # node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 1-cap/package-lock.json
    - name: Install Dependencies
      run: |
        LOG_LEVEL=${{ github.event.inputs.log-level || 'info' }}
        echo "Log level is set to $LOG_LEVEL"
        npm install --loglevel $LOG_LEVEL
    - uses: actions/upload-artifact@v2
      with:
        name: node_modules-${{ matrix.node-version }}
        path: ./1-cap/node_modules/

  build:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-cap
    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        # node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # path to cache file relative to the root of the repository
        cache-dependency-path: 1-cap/package-lock.json
    - run: echo "I'm running to build a nodejs app"
    # - uses: actions/download-artifact@v2
    #   with:
    #     name: node_modules-${{ matrix.node-version }}
    - run: npm run build --if-present

  test:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-cap
    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        # node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # path to cache file relative to the root of the repository
        cache-dependency-path: 1-cap/package-lock.json
    - run: echo "I'm running to build a nodejs app"
    # - uses: actions/download-artifact@v2
    #   with:
    #     name: node_modules-${{ matrix.node-version }}
    - run: npm run test
  
  

